version: '3.9'

services:
  postgres:
    container_name: clinic_db
    image: 'postgres:15'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: docker@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: